description: mathqa few-shot prompting experiments

env_defaults:
  JOB_GPUS: 16

environment:
  registry: grail.azurecr.io
  username: grail
  image: trace-codegen-pl:latest
  setup:
    - pip install -r requirements.txt
    - python -m nltk.downloader punkt

code:
  local_dir: $CONFIG_DIR/..

storage:
  data:
    storage_account_name: wuphillyblob 
    container_name: trace-codegen-data
    local_dir: /mnt/trace-codegen-data

data:
  local_dir: data/mathqa
  remote_dir: data/mathqa
  storage_id: data

jobs:
  - name: gpt-j-few-shot-prompting
    sku: 32G$JOB_GPUS@westus2,westus3,redmond,eastus
    # sku: G$JOB_GPUS
    command:
      - bash amulet/mathqa-prompting.sh --trainer.gpus $JOB_GPUS
